// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg4gOUCSubbRvxDPDbJ-iVI8NVn8WMvSo',
    appId: '1:559374436878:web:ba4a1e3cc148247a390a5f',
    messagingSenderId: '559374436878',
    projectId: 'odin-69af8',
    authDomain: 'odin-69af8.firebaseapp.com',
    storageBucket: 'odin-69af8.appspot.com',
    measurementId: 'G-NNE5W8C4E2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCflnOqv_5GfkSTxSdPLJi49j_Qgrbj3M',
    appId: '1:559374436878:android:759c7b58f45cb20a390a5f',
    messagingSenderId: '559374436878',
    projectId: 'odin-69af8',
    storageBucket: 'odin-69af8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRP3qz04Pxsa1mNU3SpsF7ntZ1FYIRJgk',
    appId: '1:559374436878:ios:df98f3bb0b611ea3390a5f',
    messagingSenderId: '559374436878',
    projectId: 'odin-69af8',
    storageBucket: 'odin-69af8.appspot.com',
    iosClientId: '559374436878-45p7n0hf9sdnlvkdffakce6tj8ls2q06.apps.googleusercontent.com',
    iosBundleId: 'com.example.odin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRP3qz04Pxsa1mNU3SpsF7ntZ1FYIRJgk',
    appId: '1:559374436878:ios:df98f3bb0b611ea3390a5f',
    messagingSenderId: '559374436878',
    projectId: 'odin-69af8',
    storageBucket: 'odin-69af8.appspot.com',
    iosClientId: '559374436878-45p7n0hf9sdnlvkdffakce6tj8ls2q06.apps.googleusercontent.com',
    iosBundleId: 'com.example.odin',
  );
}
