// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZuBM5e5JaNmjWt6SVgH8FhZ8JtLYnPgk',
    appId: '1:610285270739:web:229a9af83c47b07f52c626',
    messagingSenderId: '610285270739',
    projectId: 'grassroot-de928',
    authDomain: 'grassroot-de928.firebaseapp.com',
    databaseURL: 'https://grassroot-de928.firebaseio.com',
    storageBucket: 'grassroot-de928.appspot.com',
    measurementId: 'G-7QRBR84HEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy4UtTLU-zzhhWM9e4eUu7I7a6ky2eSlc',
    appId: '1:610285270739:android:90dd4b411a1e083852c626',
    messagingSenderId: '610285270739',
    projectId: 'grassroot-de928',
    databaseURL: 'https://grassroot-de928.firebaseio.com',
    storageBucket: 'grassroot-de928.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjx1SKKnrVruOOJCmO2qH9krvPExWAnc8',
    appId: '1:610285270739:ios:eac876458edb1ab852c626',
    messagingSenderId: '610285270739',
    projectId: 'grassroot-de928',
    databaseURL: 'https://grassroot-de928.firebaseio.com',
    storageBucket: 'grassroot-de928.appspot.com',
    androidClientId: '610285270739-6ag619ii9ai22tfum9f41f9hsb7pk9pc.apps.googleusercontent.com',
    iosClientId: '610285270739-egeqbbpq5af7onu63l3q8fjh7gtajqh3.apps.googleusercontent.com',
    iosBundleId: 'com.example.odin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjx1SKKnrVruOOJCmO2qH9krvPExWAnc8',
    appId: '1:610285270739:ios:eac876458edb1ab852c626',
    messagingSenderId: '610285270739',
    projectId: 'grassroot-de928',
    databaseURL: 'https://grassroot-de928.firebaseio.com',
    storageBucket: 'grassroot-de928.appspot.com',
    androidClientId: '610285270739-6ag619ii9ai22tfum9f41f9hsb7pk9pc.apps.googleusercontent.com',
    iosClientId: '610285270739-egeqbbpq5af7onu63l3q8fjh7gtajqh3.apps.googleusercontent.com',
    iosBundleId: 'com.example.odin',
  );
}
